### ISSUE TITLE
Stackoverflow with hsqldb in CC

### ISSUE THREAD

**Issue by stil4m** [stil4m/software-evolution-series-1#5]
Stackoverflow with hsqldb in CC.

We should first check which Java method analysis results in this error. Log the `loc`.

**Comment by stil4m** [comment]
This problem remains while using the fix from #6

**Comment by stil4m** [comment]
Changing stack size to `-Xss80m` does not help

**Comment by pacbeckh** [comment]
Fixed it by using createASTFromFile instead of getMethodASTEclipse
